name = "MedievalCraft"
author = "YourMom"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f1522a787bcc77585d9469b2b648568672dc422a589d71567f1776c6d57cc1c"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
