name = "MedievalCraft"
author = "YourMom"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d3833c4aa9c16a3bf3d5b409b483cf09f21e7bb8fb8a38d871808c58755b81d"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
