name = "MedievalCraft"
author = "YourMom"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8cb3db8bf7f9ac8e8477d2d0c3349d32db44d9828364c4ee35704823b720e55"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
