name = "MedievalCraft"
author = "YourMom"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1165cf7b962aa22519c16827fc67668e95a457e3f75cbefbe594b9d183924153"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
