name = "MedievalCraft"
author = "YourMom"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cc25c8b5f08d40353d2ccca0a7e73068f0daa0005b4cce2cb37f53de140b3c6"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
