name = "MedievalCraft"
author = "YourMom"
version = "1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "341dc2d9005a2149ca7870ab1f341060db7e3754e36006ebd4a6b48b87939576"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
